[tool.poetry]
name = "model_trainer"
version = "1.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"