[tool.poetry]
name = "prediction-worker"
version = "1.0.0"
description = ""
authors = []
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"